on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Update

jobs:
  pacviz_update:
    runs-on: ubuntu-latest
    name: pacviz updates
    steps:
      - uses: actions/checkout@v2
      - name: Check and Build
        run: | 
          install.packages('devtools')
          devtools::check(document=TRUE, manual=TRUE, cran=TRUE, vignettes=TRUE)
          devtools::build(manual=TRUE, vignettes=TRUE)
        shell: Rscript {0}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
